[tool.poetry]
name = "nexus-client-sdk"
version = "0.0.0"
description = "Nexus SDK library for Python."
authors = ["ECCO Sneaks & Data <esdsupport@ecco.com>"]
maintainers = ["ECCO Sneaks & Data <esdsupport@ecco.com>"]
license = 'Apache-2.0'
readme = "README.md"
repository = 'https://github.com/SneaksAndData/nexus-sdk-py'
include = [
    { path = "nexus_client_sdk/.extensions/nexus_sdk.so", format = ["wheel"] }
]

[tool.poetry.dependencies]
python = ">=3.11, <3.13"
adapta = { version = "^3.6.0", extras = ["aws", "storage", "datadog"] }
injector = "^0.22.0"
dynaconf = "^3.2"

[tool.poetry.group.dev.dependencies]
pytest = "^8"
pytest-mock = "^3"
pytest-xdist = "^3"
pytest-asyncio = "^1.1"
pytest-cov = "^2.12.1"
pylint = "^3"
black = "^23"
wheel = "^0.42.0"
pyupgrade = "^3"
scylla-driver = "^3"

[tool.black]
line-length = 120

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "session"
asyncio_default_test_loop_scope = "session"
asyncio_mode = "auto"
asyncio_debug = "false"
testpaths = [
    "tests"
]

[tool.coverage.report]
exclude_also = [
    # Don't complain about missing debug-only code:
    "def __repr__",
    "if self\\.debug",
    # Don't complain if tests don't hit defensive assertion code:
    "raise AssertionError",
    "raise NotImplementedError",
    # Don't complain if non-runnable code isn't run:
    "if 0:",
    "if __name__ == .__main__.:",
    # Don't complain about abstract methods, they aren't run:
    "@(abc\\.)?abstractmethod",
]
omit = [
    # omit custom modules
    "nexus_client_sdk/nexus/modules/*",
]

[build-system]
requires = ["poetry-core>=1.2.0"]
build-backend = "poetry.core.masonry.api"
