[tool.poetry]
name = "nexus-sdk"
version = "0.0.0"
description = "Nexus SDK library for Python."
authors = ["ECCO Sneaks & Data <esdsupport@ecco.com>"]
maintainers = ["ECCO Sneaks & Data <esdsupport@ecco.com>"]
license = 'Apache 2.0'
readme = "README.md"
repository = 'https://github.com/SneaksAndData/nexus-sdk-py'
include = [
    { path = "nexus_sdk/.extensions/nexus_sdk.so", format = ["sdist", "wheel"] }
]

[tool.poetry.dependencies]
python = ">=3.11, <3.13"
#nexus-sdk = [
#    { url = "https://github.com/SneaksAndData/nexus-sdk-go/releases/download/v0.1.2/nexus_sdk_darwin_arm64.tar.gz", platform = "darwin" },
#    { url = "https://github.com/SneaksAndData/nexus-sdk-go/releases/download/v0.1.2/nexus_sdk_linux_arm64.tar.gz", platform = "linux", markers = "platform_machine == 'arm64'" },
#    { url = "https://github.com/SneaksAndData/nexus-sdk-go/releases/download/v0.1.2/nexus_sdk_linux_amd64.tar.gz", platform = "linux", markers = "platform_machine == 'amd64'" }
#]


[tool.poetry.group.dev.dependencies]
pytest = "^7.1"
pytest-mock = "~3.6.1"
pytest-xdist = "~3.5.0"
pytest-asyncio = "~0.23.3"
pytest-cov = "~2.12"
pylint = "^3"
black = "^23"

[tool.black]
line-length = 120

[build-system]
requires = ["poetry-core>=1.2.0"]
build-backend = "poetry.core.masonry.api"
