[tool.poetry]
name = "nexus-client-sdk"
version = "0.0.0"
description = "Nexus SDK library for Python."
authors = ["ECCO Sneaks & Data <esdsupport@ecco.com>"]
maintainers = ["ECCO Sneaks & Data <esdsupport@ecco.com>"]
license = 'Apache-2.0'
readme = "README.md"
repository = 'https://github.com/SneaksAndData/nexus-sdk-py'
include = [
    { path = "nexus_client_sdk/.extensions/nexus_sdk.so", format = ["wheel"] }
]

[tool.poetry.dependencies]
python = ">=3.11, <3.13"
adapta = { version = "^3.5.1", extras = ["aws", "storage", "datadog"] }
injector = "^0.22.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8"
pytest-mock = "^3"
pytest-xdist = "^3"
pytest-asyncio = "^1.1"
pytest-cov = "^2.12.1"
locust = "^2.14.2"
pylint = "^3"
black = "^23"
wheel = "^0.42.0"
pyupgrade = "^3"
scylla-driver = "^3"

[tool.black]
line-length = 120

[build-system]
requires = ["poetry-core>=1.2.0"]
build-backend = "poetry.core.masonry.api"
