apiVersion: science.sneaksanddata.com/v1
kind: NexusAlgorithmWorkgroup
metadata:
  name: default
  namespace: nexus
spec:
  affinity: {}
  cluster: standalone
  description: Default workgroup
  tolerations: []