[algorithm]
# Name of this algorithm in the Nexus deployment
name = "hello-world"


[nexus_client]
receiver_url = "http://localhost:8081"
scheduler_url = "http://localhost:8080"

[result]
# Storage client to use when saving serialized result and generating pre-signed URL for it
storage_client_class = "adapta.storage.blob.s3_storage_client.S3StorageClient"

# Base path to use when recording results. Protocol must be supported by storage_client_class
output_path = "s3a://nexus-sdk-tests/result"

# RESULT SERIALIZERS - classes used to serialize AlgorithmResult objects to desired formats
[result.serializers]
json_format = "adapta.storage.models.formatters.PandasDataFrameJsonSerializationFormat"

[telemetry]
# Base path to use when recording input and user telemetry
output_path = "s3a://nexus-sdk-tests/telemetry"

# INPUTS - configuration for data read interfaces
[inputs]

sockets = []

[inputs.qes]
connection_string = "qes://engine=LOCAL;plaintext_credentials={};settings={}"

[logging]
# Global template to apply to ALL log messages emitted by framework loggers. This setting conflicts with
# with_log_enricher() and might be removed in the future
fixed_template = ""

# Delimiter to use for global template
fixed_template_delimiter = ""

# framework log level
log_level = "INFO"

[logging.datadog]
logger_configuration = "{'buffer_size': 1}"

[metrics]
# Implementation of MetricsProvider used to submit default framework runtime and user-level metrics
provider = "adapta.metrics.providers.datadog_provider.DatadogMetricsProvider"

# Configuration for the metrics provider (JSON string)
provider_configuration = '{"init_args": {"metric_namespace": "sdk"}, "protocol": "uds"}'