name: Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions: {}

jobs:
  codestyle:
    name: codestyle
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: '3.11.x'
          architecture: 'x64'

      - name: Install Poetry and dependencies
        uses: SneaksAndData/github-actions/install_poetry@6c8187f0d8c167a9410a76bed2e98409449ed495 # v0.1.11
        with:
          install_extras: all

      - name: Lint
        env:
          PROJECT_NAME: nexus_client_sdk
        run: |
          set -euo pipefail
          find "$PROJECT_NAME" -type f -name "*.py" | xargs poetry run pylint

      - name: Black
        run: |
          set -euo pipefail
          poetry run black . --check --diff
