name: Validate code

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  pull-requests: write
  contents: read

jobs:
  validate_commit_py311:
    name: Validate commit on Python 3.11
    runs-on: ubuntu-latest
    if: ${{ github.ref != 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          #architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

      - name: Create Controller Kind Cluster
        uses: helm/kind-action@main
        with:
          cluster_name: 'nexus-controller'
          cloud_provider: true

      - name: Create Shard Kind Cluster
        uses: helm/kind-action@main
        with:
          cluster_name: 'nexus-shard-0'

      - name: Install Nexus Stack
        run: |
          helm dependency build ./.helm \
          && helm install nexus-test-stack --kube-context kind-nexus-controller --namespace nexus --create-namespace --version 0.0.0 --set dockerServiceType=linux --no-hooks ./.helm \
          && helm upgrade nexus-test-stack --kube-context kind-nexus-controller --namespace nexus --create-namespace --set dockerServiceType=linux ./.helm
          
          helm install nexus-test-stack --kube-context kind-nexus-shard-0 --namespace nexus --create-namespace --version 0.0.0 --set dockerServiceType=linux --no-hooks ./.helm \
          && helm upgrade nexus-test-stack --kube-context kind-nexus-shard-0 --namespace nexus --create-namespace --set dockerServiceType=linux ./.helm

      - name: Launch Compose Stack
        run: |
          mkdir -p ./test-resources/kubecfg/shards
          kind export kubeconfig --name nexus-controller --kubeconfig ./test-resources/kubecfg/controller
          kind export kubeconfig --name nexus-shard-0 --kubeconfig ./test-resources/kubecfg/shards/kind-nexus-shard-0.kubeconfig
          
          chmod 777 ./test-resources/kubecfg/controller
          chmod 777 ./test-resources/kubecfg/shards/kind-nexus-shard-0.kubeconfig
  
          docker compose up --quiet-pull -d

      - name: Get Compose Logs
        if: always()
        run: docker compose logs

      - name: Download C-Shared Build of Go SDK
        run: |
          set -e
          
          cext_version=$(cat nexus_client_sdk/.extensions/cext_version)
          
          curl -L https://github.com/SneaksAndData/nexus-sdk-go/releases/download/v$cext_version/nexus_sdk_linux_amd64.tar.gz > nexus_sdk_linux_amd64.tar.gz
          mkdir cext && tar -xvzf nexus_sdk_linux_amd64.tar.gz -C cext && mv cext/dist/nexus_sdk_linux_amd64.so nexus_client_sdk/.extensions/nexus_sdk.so   

      - name: Install Poetry and dependencies
        uses: SneaksAndData/github-actions/install_poetry@v0.1.11
        with:
          install_extras: all

      - name: Unit test
        env:
          NEXUS__SDK_LOG_LEVEL: INFO
        run: |
          set -euxo pipefail
          
          poetry run pytest -n auto --dist loadgroup --doctest-modules --junitxml=junit/test-results.xml --cov=. --cov-report=term-missing:skip-covered | tee pytest-coverage.txt

      - name: Get Nexus Job/Pod Data
        if: always()
        run: |
          kubectl get jobs -n nexus --context kind-nexus-shard-0 && kubectl get pods -n nexus --context kind-nexus-shard-0 && kubectl logs -n nexus --context kind-nexus-shard-0 -l science.sneaksanddata.com/algorithm-template-name=hello-world

      - name: Get Compose Logs (2)
        if: always()
        run: docker compose logs

      - name: Publish Code Coverage
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./junit/test-results.xml
