name: Validate code

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  pull-requests: write
  contents: read

jobs:
  validate_commit_py311:
    name: Validate commit on Python 3.11
    runs-on: ubuntu-latest
    if: ${{ github.ref != 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          #architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

      - name: Setup just
        uses: extractions/setup-just@v3

      - name: Setup integration tests
        run: just up

      - name: Download C-Shared Build of Go SDK
        run: |
          set -e
          
          cext_version=$(cat nexus_client_sdk/.extensions/cext_version)
          
          curl -L https://github.com/SneaksAndData/nexus-sdk-go/releases/download/v$cext_version/nexus_sdk_linux_amd64.tar.gz > nexus_sdk_linux_amd64.tar.gz
          mkdir cext && tar -xvzf nexus_sdk_linux_amd64.tar.gz -C cext && mv cext/dist/nexus_sdk_linux_amd64.so nexus_client_sdk/.extensions/nexus_sdk.so   

      - name: Install Poetry and dependencies
        uses: SneaksAndData/github-actions/install_poetry@v0.1.11
        with:
          install_extras: all

      - name: Unit test
        env:
          NEXUS__SDK_LOG_LEVEL: INFO
          ROOT_PATH_FOR_DYNACONF: ${{ github.workspace }}/tests
          CONFIG_EXTENSION_PATH_OVERRIDE: ${{ github.workspace }}/tests/config_extensions
        run: |
          set -euo pipefail
          
          poetry run pytest -n auto --dist loadgroup --doctest-modules --junitxml=junit/test-results.xml --cov=. --cov-report=term-missing:skip-covered | tee pytest-coverage.txt

      - name: Get logs from application pods
        if: always()
        run: |
          kubectl describe pods --namespace default || true

      - name: Publish Code Coverage
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./junit/test-results.xml
