name: Validate code

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions: {}

jobs:
  validate_commit_py311:
    name: Validate commit
    runs-on: ubuntu-latest
    permissions:
      id-token: write      # required for dependabot PRs
      pull-requests: write # required for dependabot PRs; coverage PR comment
      contents: read       # required for dependabot PRs
    if: ${{ github.ref != 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: '3.11.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          #architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

      - name: Setup just
        uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4.0.0

      - name: Setup integration tests
        run: just up

      - name: Download C-Shared Build of Go SDK
        run: |
          set -e
          
          cext_version=$(cat nexus_client_sdk/.extensions/cext_version)
          
          curl -L https://github.com/SneaksAndData/nexus-sdk-go/releases/download/v$cext_version/nexus_sdk_linux_amd64.tar.gz > nexus_sdk_linux_amd64.tar.gz
          mkdir cext && tar -xvzf nexus_sdk_linux_amd64.tar.gz -C cext && mv cext/dist/nexus_sdk_linux_amd64.so nexus_client_sdk/.extensions/nexus_sdk.so   

      - name: Install Poetry and dependencies
        uses: SneaksAndData/github-actions/install_poetry@e3f4ea513c548adf4e774364872966d0d4a3d2fe # v0.1.12
        with:
          install_extras: all

      - name: Unit test
        env:
          NEXUS__SDK_LOG_LEVEL: INFO
          ROOT_PATH_FOR_DYNACONF: ${{ github.workspace }}/tests
          CONFIG_EXTENSION_PATH_OVERRIDE: ${{ github.workspace }}/tests/config_extensions
        run: |
          set -euo pipefail
          
          poetry run pytest -n auto --dist loadgroup --doctest-modules --junitxml=junit/test-results.xml --cov=. --cov-report=term-missing:skip-covered | tee pytest-coverage.txt

      - name: Get logs from application pods
        if: always()
        run: |
          kubectl describe pods --namespace default || true

      - name: Publish Code Coverage
        uses: MishaKav/pytest-coverage-comment@432ac90e8d345c93e1d90ee0838b35913abc9c9b # v1.12.2
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./junit/test-results.xml
