name: Create development package

on: issue_comment

permissions: {}

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # create_package posts a comment with the package version
    if: ${{ github.event.issue.pull_request && github.event.comment.body == 'create_package' && github.event.issue.state == 'open' }}
    steps:
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: '3.11.x'
          architecture: 'x64'
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: refs/pull/${{github.event.issue.number}}/merge
          fetch-depth: 0
          persist-credentials: false
      - name: Install Poetry and dependencies
        uses: SneaksAndData/github-actions/install_poetry@e3f4ea513c548adf4e774364872966d0d4a3d2fe # v0.1.12
        with:
          skip_dependencies: true
      - name: Create package
        uses: SneaksAndData/github-actions/create_package@e3f4ea513c548adf4e774364872966d0d4a3d2fe # v0.1.12
        with:
          public_package_index_token: ${{ secrets.PYPI_API_TOKEN }}
          package_name: nexus-sdk
